services:
  # Python Face Recognition Service
  - type: web
    name: face-recognition-service
    env: python
    plan: starter
    buildCommand: pip install -r requirements.txt
    startCommand: python face_recognition_service.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: PORT
        value: 8000

  # Express.js Backend Service
  - type: web
    name: gym-sass-backend
    env: node
    plan: starter
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000
      - key: PYTHON_FACE_SERVICE_URL
        value: https://face-recognition-service.onrender.com
      # Add your other environment variables here
      # - key: DATABASE_URL
      #   value: your_database_url
      # - key: CLOUDINARY_CLOUD_NAME
      #   value: your_cloudinary_cloud_name
      # - key: CLOUDINARY_API_KEY
      #   value: your_cloudinary_api_key
      # - key: CLOUDINARY_API_SECRET
      #   value: your_cloudinary_api_secret 